/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD1.h"
#include "LCD2.h"
#include "XBee.h"
#include "GSM.h"
#include "WIFI.h"
#include "PSOC.h"
#include "mosi_aliases.h"
#include "mosi.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "sclk_aliases.h"
#include "sclk.h"
#include "ss0_aliases.h"
#include "ss0.h"
#include "miso_aliases.h"
#include "miso.h"
#include "SelectSS.h"
#include "ss1_aliases.h"
#include "ss1.h"
#include "Psoc_status_aliases.h"
#include "Psoc_status.h"
#include "PKey_aliases.h"
#include "PKey.h"
#include "led_aliases.h"
#include "led.h"
#include "EEPROM.h"
#include "timer_clock.h"
#include "Timer_psoc.h"
#include "isr_psoc.h"
#include "Timer_LCD.h"
#include "isr_LCD.h"
#include "LCD1_IntClock.h"
#include "LCD2_IntClock.h"
#include "XBee_IntClock.h"
#include "GSM_IntClock.h"
#include "WIFI_IntClock.h"
#include "PSOC_IntClock.h"
#include "SPIM_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

